//! Structured TOML configuration for OpenPulse TNC binaries.
//!
//! Reads `~/.config/openpulse/config.toml` and returns an [`OpenpulseConfig`]
//! with built-in defaults applied for any missing fields.
//!
//! Precedence: CLI flag overrides > config file > built-in defaults.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("failed to read config file: {0}")]
    Io(#[from] std::io::Error),
    #[error("failed to parse config file: {0}")]
    Parse(#[from] toml::de::Error),
}

/// Top-level configuration.
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
#[serde(default)]
pub struct OpenpulseConfig {
    pub station: StationConfig,
    pub modem: ModemConfig,
    pub ardop: ArdopConfig,
    pub kiss: KissConfig,
    pub logging: LoggingConfig,
    pub relay: RelayConfig,
    pub trust: TrustConfig,
}

/// Station identity.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct StationConfig {
    pub callsign: String,
    pub grid_square: String,
}

/// Modem defaults shared by all TNC binaries.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct ModemConfig {
    /// Default modulation mode (e.g. `"BPSK250"`).
    pub mode: String,
    /// PTT backend: `none`, `rts`, `dtr`, `vox`, or `rigctld`.
    pub ptt_backend: String,
}

/// ARDOP TNC service settings.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct ArdopConfig {
    pub bind_addr: String,
    pub cmd_port: u16,
    pub data_port: u16,
}

/// KISS TNC service settings.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct KissConfig {
    pub bind_addr: String,
    pub port: u16,
}

/// Logging configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct LoggingConfig {
    /// `tracing` level filter: `error`, `warn`, `info`, `debug`, or `trace`.
    pub level: String,
}

/// Multi-hop relay settings.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(default)]
pub struct RelayConfig {
    pub enable: bool,
    pub max_hops: u8,
}

/// Trust store settings.
#[derive(Debug, Clone, Deserialize, Serialize, Default)]
#[serde(default)]
pub struct TrustConfig {
    /// Path to the local trust store. Empty string uses the platform default.
    pub store_path: String,
}

// ── Defaults ──────────────────────────────────────────────────────────────────

impl Default for StationConfig {
    fn default() -> Self {
        Self {
            callsign: "N0CALL".into(),
            grid_square: "AA00".into(),
        }
    }
}

impl Default for ModemConfig {
    fn default() -> Self {
        Self {
            mode: "BPSK250".into(),
            ptt_backend: "none".into(),
        }
    }
}

impl Default for ArdopConfig {
    fn default() -> Self {
        Self {
            bind_addr: "127.0.0.1".into(),
            cmd_port: 8515,
            data_port: 8516,
        }
    }
}

impl Default for KissConfig {
    fn default() -> Self {
        Self {
            bind_addr: "127.0.0.1".into(),
            port: 8100,
        }
    }
}

impl Default for LoggingConfig {
    fn default() -> Self {
        Self {
            level: "info".into(),
        }
    }
}

impl Default for RelayConfig {
    fn default() -> Self {
        Self {
            enable: false,
            max_hops: 3,
        }
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Returns the platform-standard config file path.
///
/// On Linux: `~/.config/openpulse/config.toml`
/// On macOS: `~/Library/Application Support/openpulse/config.toml`
/// On Windows: `%APPDATA%\openpulse\config.toml`
pub fn default_config_path() -> Option<PathBuf> {
    dirs::config_dir().map(|d| d.join("openpulse").join("config.toml"))
}

/// Load config from the platform-standard path. Returns `OpenpulseConfig::default()`
/// if the file does not exist.
pub fn load() -> Result<OpenpulseConfig, ConfigError> {
    match default_config_path() {
        Some(path) => load_from(&path),
        None => Ok(OpenpulseConfig::default()),
    }
}

/// Load config from `path`. Returns `OpenpulseConfig::default()` if the file does
/// not exist.
pub fn load_from(path: &Path) -> Result<OpenpulseConfig, ConfigError> {
    if !path.exists() {
        return Ok(OpenpulseConfig::default());
    }
    let content = std::fs::read_to_string(path)?;
    let config: OpenpulseConfig = toml::from_str(&content)?;
    Ok(config)
}

/// Returns a commented TOML configuration template for `openpulse config init`.
pub fn init_template() -> String {
    r#"# OpenPulse configuration file
# Generated by: openpulse config init
#
# Place this file at:
#   Linux/BSDs : ~/.config/openpulse/config.toml
#   macOS      : ~/Library/Application Support/openpulse/config.toml
#   Windows    : %APPDATA%\openpulse\config.toml
#
# All fields are optional; built-in defaults are used for any missing values.

[station]
# Your amateur radio callsign.
callsign = "N0CALL"
# Maidenhead grid square locator.
grid_square = "AA00"

[modem]
# Default modulation mode used when no --mode flag is provided.
# Available: BPSK31, BPSK63, BPSK100, BPSK250, QPSK125, QPSK250, QPSK500,
#            QPSK1000, 8PSK500, 8PSK1000, FSK4-ACK
mode = "BPSK250"
# PTT backend: none | rts | dtr | vox | rigctld
ptt_backend = "none"

[ardop]
# IP address the ARDOP TNC listens on.
bind_addr = "127.0.0.1"
# ARDOP command port.
cmd_port = 8515
# ARDOP data port.
data_port = 8516

[kiss]
# IP address the KISS TNC listens on.
bind_addr = "127.0.0.1"
# KISS TCP port.
port = 8100

[logging]
# Log verbosity: error | warn | info | debug | trace
level = "info"

[relay]
# Enable multi-hop relay forwarding.
enable = false
# Maximum relay hop count.
max_hops = 3

[trust]
# Path to the local trust store directory. Empty = platform default.
store_path = ""
"#
    .to_string()
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn load_defaults_when_no_file() {
        let path = std::env::temp_dir().join("openpulse_config_nonexistent_xyz.toml");
        let _ = std::fs::remove_file(&path);
        let cfg = load_from(&path).unwrap();
        assert_eq!(cfg.station.callsign, "N0CALL");
        assert_eq!(cfg.ardop.cmd_port, 8515);
        assert_eq!(cfg.ardop.data_port, 8516);
        assert_eq!(cfg.kiss.port, 8100);
        assert_eq!(cfg.modem.mode, "BPSK250");
        assert_eq!(cfg.logging.level, "info");
        assert!(!cfg.relay.enable);
        assert_eq!(cfg.relay.max_hops, 3);
    }

    #[test]
    fn cli_override_pattern() {
        // CLI flag > config > default: simulate by loading config then applying
        // an Option<T> override, the pattern used by TNC binaries.
        let path = std::env::temp_dir().join("openpulse_config_override_test.toml");
        {
            let mut f = std::fs::File::create(&path).unwrap();
            writeln!(f, "[ardop]").unwrap();
            writeln!(f, "cmd_port = 9000").unwrap();
            writeln!(f, "data_port = 9001").unwrap();
        }
        let mut cfg = load_from(&path).unwrap();
        assert_eq!(cfg.ardop.cmd_port, 9000);

        // CLI flag supplied → overrides config value.
        let cli_cmd_port: Option<u16> = Some(7777);
        if let Some(p) = cli_cmd_port {
            cfg.ardop.cmd_port = p;
        }
        assert_eq!(cfg.ardop.cmd_port, 7777);
        // Unset CLI flag → config value retained.
        assert_eq!(cfg.ardop.data_port, 9001);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn missing_fields_get_defaults() {
        let path = std::env::temp_dir().join("openpulse_config_partial_test.toml");
        {
            let mut f = std::fs::File::create(&path).unwrap();
            // Only set callsign; everything else should come from Default.
            writeln!(f, "[station]").unwrap();
            writeln!(f, r#"callsign = "K1ABC""#).unwrap();
        }
        let cfg = load_from(&path).unwrap();
        assert_eq!(cfg.station.callsign, "K1ABC");
        // Fields not in the file use built-in defaults.
        assert_eq!(cfg.station.grid_square, "AA00");
        assert_eq!(cfg.ardop.cmd_port, 8515);
        assert_eq!(cfg.modem.ptt_backend, "none");
        let _ = std::fs::remove_file(&path);
    }
}
