URL = "https://dc0sk.github.io/OpenPulseHF"
FOOTER = "OpenPulseHF — an open-source project by Simon Keimer (DC0SK)"

USE_CASES = [
 ("Use case 1 — messaging with no infrastructure", [
   "A sailor mid-Atlantic. A field team beyond cellular coverage. A station in a",
   "region where the network is simply not there.",
   "",
   "HF needs no infrastructure between the two endpoints — only propagation.",
   "",
   "What OpenPulseHF provides:",
   "• Full B2F / Winlink session driver, and a direct CMS gateway over TCP",
   "• ARDOP TCP interface speaking the command set Pat already expects",
   "• Compression, segmentation and reassembly for messages over 255 bytes",
   "",
   "Honest scope: the Winlink stack is implemented and tested end to end in",
   "loopback. Type D (gzip) is supported; Type C (LZHUF) is refused rather than",
   "half-supported."]),

 ("Use case 2 — emergency communications", [
   "When the infrastructure is the casualty: storm, flood, earthquake, outage.",
   "",
   "What matters in that hour is not throughput. It is: does a message get",
   "through at all, and can the recipient tell who sent it?",
   "",
   "What OpenPulseHF provides:",
   "• A sub-floor weak-signal waveform (MFSK16) for when the link is marginal",
   "• An adaptive ladder that falls back rather than failing outright",
   "• A signed handshake, so a station's identity is cryptographically checkable",
   "• Automatic station identification, in voice or CW, per regulation",
   "",
   "Honest scope: authentication answers 'who is this?'. It deliberately does",
   "NOT encrypt — amateur regulations forbid obscuring meaning."]),

 ("Use case 3 — moving files between stations", [
   "Not every payload is a message. A configuration, a log, an image, a small",
   "dataset — where the only path between two points is HF.",
   "",
   "What OpenPulseHF provides:",
   "• A direct peer-to-peer file-transfer protocol with offer / accept / reject",
   "• Block-level resume — a transfer interrupted by a fade continues, it does",
   "  not restart",
   "• Airtime-bounded bursts, so a long transfer does not monopolise a shared",
   "  channel or hold PTT beyond what the rig and the rules allow",
   "• Manifest verification: SHA-256 plus a signature, so corruption and",
   "  substitution are both detectable",
   "",
   "Honest scope: proven across two real daemons over a simulated channel and",
   "on wired rigs. On-air validation of this path is still outstanding."]),

 ("Use case 4 — finding a peer, then linking to it", [
   "The awkward part of HF is rarely the modem. It is knowing who is audible,",
   "on which frequency, right now.",
   "",
   "What OpenPulseHF provides:",
   "• JS8-compatible beaconing and decoding — interoperable with an established",
   "  weak-signal ecosystem rather than inventing a private one",
   "• A peer cache scored by link quality and trust",
   "• Rendezvous: propose, accept, then a scheduled QSY to a working frequency",
   "• Automatic handoff into a full HPX data session on arrival",
   "",
   "Honest scope: the protocol layers are complete and tested, including two",
   "runtimes exchanging real GFSK audio. The on-air phase is not yet done —",
   "and the beacon is off by default, behind an explicit configuration."]),

 ("Use case 5 — a platform for waveform work", [
   "The use case that shaped the architecture: trying a new waveform without",
   "rebuilding a modem around it.",
   "",
   "What OpenPulseHF provides:",
   "• One plugin trait — a waveform is self-contained and drops in",
   "• Eight seeded channel-impairment models, so a result is reproducible",
   "• A signal-path testbench: TX, noise, mixed and decoded taps side by side",
   "• A mode × channel test matrix runner producing comparable reports",
   "• A two-station link simulator measuring effective two-way throughput",
   "",
   "This is also why the project is strict about evidence: a platform whose",
   "measurements cannot be trusted is worse than no platform at all."]),
    ("Use case 6 — one program, not a shelf of them",
     ["A typical HF data station runs several separate pieces. OpenPulseHF is one binary that covers "
      "what most of them do — and talks the same protocols, so existing clients keep working.",
      "",
      "REPLACED BY THE DAEMON:",
      "  · a soundcard TNC — ARDOP TCP and KISS/AX.25 ports, so Pat and any AX.25 client connect unchanged",
      "  · the modem itself — 16 waveform plugins, BPSK31 through 64QAM, OFDM and SC-FDMA",
      "  · a separate PTT tool — serial RTS/DTR, VOX, rigctld/CAT, CM108 and GPIO backends built in",
      "  · a separate rig-control step — frequency and mode set over CAT from the same process",
      "  · a Winlink transport — B2F session driver and a direct CMS gateway",
      "  · a digipeater or relay box — repeater and mesh nodes are the same binary with a flag",
      "",
      "STILL NEEDED: the radio, the audio interface, and a Winlink client if you want a mailbox UI.",
      "NOT A REPLACEMENT FOR: a hardware PACTOR modem (different, licensed waveforms) or VARA "
      "(closed protocol — we do not interoperate with it and do not claim to)."]),

    ("Use case 7 — relaying past a station you cannot",
     ["Two stations that cannot work each other directly can go through a third. The relay layer "
      "forwards signed envelopes, enforces a hop limit, suppresses duplicates, and refuses to carry "
      "traffic from a peer its trust policy rejects.",
      "",
      "  · route scoring is trust-weighted, and uses the BOTTLENECK hop, not the average — one weak "
      "hop is not averaged away by good ones",
      "  · every hop verifies the ORIGIN signature, so a relay cannot forge the sender it claims to "
      "be carrying for",
      "  · duplicates are suppressed on (session, nonce) with a TTL, so a loop dies instead of "
      "amplifying",
      "",
      "BE PRECISE ABOUT WHAT THIS IS: it forwards in real time. There is NO store-and-forward — no "
      "queue, no persistence, no delivery to a station that is not on the air right now. If the next "
      "hop is absent, the frame is dropped, not held. A real mailbox is a roadmap item, not a "
      "feature."]),

    ("Use case 8 — cross-band repeating",
     ["One station bridges two bands: receive on one, retransmit on the other. Useful when a group "
      "splits between an HF net and a local VHF/UHF simplex frequency, or when propagation favours "
      "one band at one end of a path.",
      "",
      "  · CrossBandRepeater runs full-duplex in its own thread, enabled and disabled at runtime "
      "over the daemon control port — no restart",
      "  · a configurable filter and forwarding policy decide what is worth repeating, so the "
      "repeater is not an unconditional amplifier",
      "",
      "OPERATOR RESPONSIBILITY: an automatically-keyed transmitter is a regulated thing. Station "
      "identification, band privileges and unattended-operation rules are yours to satisfy — the "
      "software emits periodic ID but cannot know your licence class or your jurisdiction."]),

    ("Use case 9 — a mesh of beacons",
     ["Mesh nodes re-broadcast signed beacons with a decrementing TTL, so a station several hops "
      "away learns that you exist, on what frequency, and with what capabilities — without any "
      "central server.",
      "",
      "  · beacons are Ed25519-signed and self-authenticating: the peer id IS the verifying key, so "
      "no key server is needed to check one",
      "  · TTL bounds the flood; duplicate suppression stops a beacon circling a loop",
      "  · what a node learns feeds the shared peer cache, which the query and routing layers read",
      "",
      "SCOPE: this spreads REACHABILITY INFORMATION — who is out there and how to reach them. It is "
      "not a data-carrying mesh network, and a beacon that arrives is evidence a path existed when "
      "it was sent, not that one exists now."]),

    ("Use case 10 — moving the QSO off a bad frequency",
     ["A frequency that worked ten minutes ago can be ruined by a new signal or a change in "
      "propagation. QSY lets two stations agree on a better one and move together, without either "
      "operator guessing where the other went.",
      "",
      "  · the scanner measures candidate frequencies and dwells on each, so the proposal is based "
      "on what was heard rather than on a guess",
      "  · the exchange is Ed25519-signed, so a third party cannot walk a QSO onto a frequency of "
      "their choosing",
      "  · both ends switch on an agreed offset, so the move is scheduled rather than raced",
      "",
      "HONEST SCOPE: the state machine, the wire format and the scan are shipped and tested; the "
      "change of frequency is proposed and accepted explicitly, not triggered automatically by a "
      "link-quality threshold. Automatic initiation is a policy decision nobody should take from "
      "the operator by default."]),

    ("Use case 11 — who is actually talking on FreeDV",
     ["FreeDV carries digital voice, and a voice you recognise is not proof of identity. This shim "
      "sends Ed25519-signed beacons through FreeDV's own data channel so a listener can verify which "
      "station is transmitting.",
      "",
      "  · runs ALONGSIDE FreeDV over its UDP data port — FreeDV itself is not modified or patched",
      "  · each beacon signs the callsign, a timestamp, a nonce, the frequency and the mode, so a "
      "capture cannot be replayed onto another frequency or another moment",
      "",
      "WHAT IT IS NOT: it does not authenticate the AUDIO. It authenticates a beacon transmitted "
      "alongside it. Somebody relaying your voice while sending their own beacons is not something "
      "this detects, and the honest claim is 'this station is on frequency and signing', not "
      "'these words came from that person'."]),

]

CONTENT_SLIDES = [
 ("Agenda", [
   "1.  Use cases — eleven things people actually do with an HF data link",
   "2.  What OpenPulseHF is — and the problem it addresses",
   "3.  What makes it different from other software and hardware modems",
   "4.  How it is developed and implemented",
   "5.  How it is tested — the layer stack, and what each layer can prove",
   "6.  Feature highlights, advanced features, measured performance",
   "7.  Current status and outlook — including what is NOT done"]),
 ("The problem: data over HF", [
   "HF gives intercontinental reach with no infrastructure — and a hostile channel.",
   "",
   "• Multipath → delay spread and frequency-selective fading",
   "• Doppler → the carrier phase reference moves under you",
   "• QRM / QRN → interference you do not control",
   "• A 2.4 kHz voice channel, shared, under strict regulatory limits",
   "",
   "A waveform that works at 20 dB SNR on a bench can decode 0 % of frames on a",
   "routine Watterson fade. That gap is the entire engineering problem."]),
 ("What OpenPulseHF is", [
   "A software modem for HF data, written in Rust.",
   "",
   "• ~165 000 lines across 24 crates, 10 waveform plugins, 5 applications",
   "• Waveforms are PLUGINS behind one trait — not a fixed mode list",
   "• 85 registered modes · 10 FEC modes · 8 channel-impairment models",
   "• Commodity hardware: PC or Raspberry Pi, any SSB transceiver",
   "• Interfaces: ARDOP TCP (Pat-compatible), KISS/AX.25, control daemon,",
   "  GUI operator panel, signal-path testbench",
   "",
   "No DSP hardware. No licence. The waveform is source."]),
 ("Where it sits", [
   "PACTOR (hardware)     excellent · proprietary · expensive · closed",
   "VARA (software)       strong performance · closed source · Windows-first",
   "ARDOP (software)      open · but a single fixed waveform family",
   "JS8Call / WSJT-X      superb weak-signal · not general data transport",
   "",
   "OpenPulseHF aims at: open source, waveform-extensible, adaptive — and",
   "honest about what has actually been measured.",
   "",
   "It interoperates where it can: the ARDOP TCP interface speaks the command",
   "set Pat expects, and the B2F / Winlink stack is implemented."]),
 ("Difference 1 — waveforms are plugins", [
   "One trait, ModulationPlugin. A waveform supplies:",
   "",
   "• modulate / demodulate, and an optional soft-LLR demodulator",
   "• frame geometry — preamble length, symbol period, frame bounds",
   "• occupied bandwidth, AFC estimator, optional preamble template",
   "",
   "Adding a waveform touches neither the engine, the ARQ layer, the daemon,",
   "nor the rate controller.",
   "",
   "Shipped: BPSK · QPSK (incl. differential) · 8PSK · 64QAM · OFDM · SC-FDMA ·",
   "pilot-framed PSK/QAM/APSK · MFSK16 · FSK4 · JS8"]),
 ("Difference 2 — the ladder adapts on EVIDENCE", [
   "A rate ladder normally climbs on an SNR estimate. Ours does too — but an",
   "SNR estimate can lie.",
   "",
   "Measured: on a fading channel a residual-based estimator folds the fade into",
   "'noise' and reads a FLAT −4 dB across 20 dB of real SNR change. The ladder",
   "then pins itself on its entry rung while delivering 20 / 20 frames.",
   "",
   "So the controller also climbs on consecutive successful DECODES, and never",
   "demotes below a level that just decoded.",
   "",
   "A decode is an observation. An SNR estimate is a model. The observation wins."]),
 ("Difference 3 — signed identity, in-band", [
   "Every session can open with a signed handshake over RF:",
   "",
   "• Ed25519 CONREQ / CONACK, trust store, policy profiles",
   "• Replay freshness — signed timestamp, bounded clock skew",
   "• ECDH-derived key authenticating the rate-control ACK channel",
   "• A post-quantum variant (ML-DSA-44 + ML-KEM-768) — format-complete",
   "",
   "This is AUTHENTICATION, not encryption — content stays in the clear, which",
   "is what amateur regulations require. It answers 'who is this?', not",
   "'what are they saying?'"]),
 ("Implementation — the shape of the code", [
   "Core         traits · framing · FEC · session state machine · trust · SAR",
   "DSP          RRC · PLL · Gardner timing · LMS/DFE equaliser · noise floor",
   "Modem        engine · scheduler · diagnostics · CSMA/DCD · channel sim",
   "Protocol     ARDOP TNC · KISS TNC · B2F/Winlink · QSY · discovery · mesh ·",
   "             file transfer · control daemon",
   "Apps         operator panel · testbench · test matrix · twin viewer · linksim",
   "",
   "Rules that hold throughout: no unwrap/expect in library paths, typed errors,",
   "and anything crossing an API boundary is serde-derived."]),
 ("Implementation — one seam, not many callers", [
   "A cross-cutting receive transform — notch, AGC, DC block — is wired at",
   "exactly ONE place: route_audio_stage(InputCapture).",
   "",
   "Why it matters. The auto-notch was originally wired in ONE caller. It worked",
   "in the receive() family and never ran in the daemon at all.",
   "",
   "Both 'we harden against interference' and 'the station could not decode'",
   "were true simultaneously.",
   "",
   "Every such feature now carries a tripwire counter, asserted through the",
   "production entry point — not through a convenience API."]),
 ("How it is developed — requirements as DATA", [
   "154 requirements and 76 capabilities live in a machine-readable file.",
   "",
   "• Tests bind to requirements IN THE CODE — // VERIFIES: REQ-…",
   "• The traceability matrix is GENERATED, never hand-typed",
   "• A trace checker runs inside the gate and fails the build on a requirement",
   "  with no test, or a production module no requirement asks for",
   "• A reachability ratchet fails on any NEW public item with no caller",
   "",
   "Not ceremony: in the last change it caught two requirements whose bindings a",
   "test rewrite had silently deleted — on a commit where all 2 385 tests passed."]),
 ("How it is developed — adversarial review", [
   "A second model reviews every design decision BEFORE implementation, and every",
   "conclusion BEFORE it enters the documentation.",
   "",
   "The rule exists because the expensive failures here are not bad code. They",
   "are CONFIDENT WRONG BELIEFS that survive long enough to be built upon.",
   "",
   "Recent example: a merged change was reviewed retrospectively and found to",
   "contain a defect that FAILED OPEN — a legal 11-character compound callsign",
   "silently dropped the station to an unverified session.",
   "",
   "Every gate passed. Every test passed. Review read a constant against its",
   "generator — a check no gate performs."]),
 ("Testing — six layers", [
   "1  Unit               183 files with inline tests — pure functions, codecs",
   "2  Integration        231 test files — engine, protocol, session, security",
   "3  Channel simulation Watterson · Gilbert-Elliott · AWGN · QRM/QRN/QSB ·",
   "                      chirp · carrier and sample-rate offset — seeded",
   "4  Virtual loopback   snd-aloop — one clock; isolates DSP from clock effects",
   "5  Dual-card rig      two sound cards, real analog path — two clocks",
   "6  On air             two stations, real transceivers, real propagation",
   "",
   "Plus a capture-replay corpus: recorded real radio audio, replayed as a",
   "regression test."]),
 ("Testing — what each layer CANNOT prove", [
   "The more useful half of the table.",
   "",
   "• A unit test cannot see a seam gap — the code is correct in isolation.",
   "• An in-process harness hands the receiver a buffer that IS the frame. Real",
   "  receivers listen for seconds with the frame somewhere inside — a whole",
   "  class of frame-LOCATION bugs was structurally invisible.",
   "• A single-clock rig cannot show sample-rate offset.",
   "• A simulation cannot show a capture AGC moving the level mid-frame.",
   "• A round-trip test cannot see a wire-format change — encoder and decoder",
   "  drift together and every test stays green.",
   "",
   "Each of these was a real defect, found only when the layer above it ran."]),
 ("Testing — the gate", [
   "One command is authoritative. It runs, without pipes hiding exit codes:",
   "",
   "   format → clippy (warnings are errors) → full workspace suite",
   "   (no-fail-fast) → requirement trace → reachability ratchet →",
   "   commit-trailer lint → documentation-ordering check",
   "",
   "Current: 316 suites · 2 408 tests · 0 failures",
   "",
   "Every new gate is SABOTAGE-VERIFIED: break the code deliberately and watch",
   "the gate fail, before trusting it. A gate nobody has watched fail is the",
   "self-consistent checker it exists to prevent."]),
 ("Feature highlights", [
   "• 85 modes across 10 waveform families, selectable at runtime",
   "• 10 FEC modes — Reed-Solomon (3 strengths), interleaved, concatenated,",
   "  soft-decision concatenated, LDPC, high-rate LDPC, turbo",
   "• 11 adaptive profiles — HF, narrowband, wideband, OFDM, pilot-framed",
   "• Adaptive ARQ with soft-LLR HARQ combining across retransmissions",
   "• Automatic notch · streaming AGC · noise-floor-tracking carrier detect",
   "• CSMA channel access · automatic station ID (voice and CW)",
   "• PTT: CAT/rigctld · serial RTS/DTR · VOX · CM108 · GPIO"]),
 ("Advanced features", [
   "Winlink / B2F     full session driver, direct CMS gateway",
   "File transfer     P2P protocol with resume, airtime-bounded bursts",
   "Discovery         JS8-compatible beaconing and rendezvous → HPX handoff",
   "QSY               signed frequency-agility protocol with scanner",
   "Mesh / repeater   TTL-bounded rebroadcast, digipeater with policy",
   "Relay             multi-hop with trust-weighted path scoring",
   "GPU               wgpu compute kernels for BPSK DSP, CPU fallback",
   "Remote control    PSK-authenticated encrypted daemon link (Noise)",
   "Post-quantum      ML-DSA-44 + ML-KEM-768 handshake — format-complete"]),
 ("Performance — measured on simulated channels", [
   "Differential QPSK rescues a dead rung:",
   "    coherent QPSK250 on a moderate fade — 0.00 at EVERY SNR up to 40 dB",
   "    QPSK250-D — recovers the same rung to ~0.65 at 20 dB",
   "",
   "MFSK16 sub-floor waveform:",
   "    beats coherent BPSK31 by ~4 dB on moderate fade, and decodes where",
   "    BPSK31 fails entirely on fast fade — at a PAPR cost",
   "",
   "On a fade, FEC is the lever — not modulation order:",
   "    BPSK31 @ 3 dB — uncoded 0.00 → coded 0.25 → strong-coded 1.00",
   "    BPSK63 @ 7 dB — coded 1.00",
   "",
   "Benchmark gate: 100 % frame pass · ≤ 20 mean state transitions"]),
 ("Performance — a result worth the detail", [
   "The signed handshake was 752 bytes on the wire: THREE SAR fragments.",
   "",
   "Three preambles, three acquisitions. On a fading channel a frame needing",
   "three independent acquisitions decodes at roughly p³ — against a background",
   "where the slow uncoded rungs decode near zero.",
   "",
   "Re-laid as a binary format: 187 bytes typical, 224 bytes for the MAXIMAL",
   "legal frame — inside a single 251-byte fragment.",
   "",
   "One acquisition instead of three. Airtime 24 s → 8 s at BPSK250.",
   "",
   "The cost was never speed. It was p³ versus p."]),
 ("Regulatory — enforced, documented, deferred", [
   "ENFORCED IN CODE",
   "• Station ID on a timer, and at the end of a transmission series (§97.119)",
   "• CW ID audio — decodable by any receiving operator, not only by us",
   "• Relay / responder / QSY paths refuse to key without a configured callsign",
   "• Bursts are duration-bounded, and the wire format is published in full",
   "",
   "DOCUMENTED — AND LEFT TO THE OPERATOR",
   "• Symbol rate per band — BPSK31/63/100/250 under 300 baud; QPSK500+ is not",
   "• Bandwidth, power, band segments — these vary by administration and licence",
   "• §97.221 automatic control point, for unattended relay operation",
   "• IARU band plans — recommendation rather than law, but widely observed",
   "",
   "The modem will generate a mode that is illegal on your frequency — a decision,",
   "not an oversight: legality depends on band, jurisdiction and licence class.",
   "Surveyed: FCC 97 · CEPT/ECC · BNetzA · Ofcom · IARU. On-air validation: deferred."]),
 ("Current status — and what is NOT done", [
   "v0.16.0, pre-1.0 · 2 408 tests green · 361 recorded change entries",
   "",
   "Proven on simulation and on wired rigs. On air, a first real over-the-air",
   "decode between two stations has been achieved.",
   "",
   "Explicitly NOT done — stated because a green suite implies otherwise:",
   "",
   "• Full on-air regulatory validation is deferred — station ID audit,",
   "  compliance report, transmitter-release timing all need the rig",
   "• The PQ handshake is format-complete but ~2.7 min at BPSK250: it buys a",
   "  FINISHED FORMAT, not a deployable feature",
   "• Some ladder floors are calibrated on simulation, not on hardware"]),
 ("Outlook", [
   "Before 1.0:",
   "",
   "• Close the pre-1.0 wire-format break window — the format freezes at the",
   "  tag, so every break lands now or never",
   "• An on-air validation campaign against the deferred items",
   "• Finish the acquisition work: preamble correlation on every mode, not",
   "  only BPSK",
   "",
   "The governing principle stays the same:",
   "",
   "    State the evidence tier. Simulation is not hardware. Hardware is not",
   "    on air. And a passing test is not proof that the thing it names is",
   "    what was measured."]),
]
