#!/usr/bin/env bash
# Loopback audio device identifiers.
# Generated by scripts/identify-loopback-audio.sh on 2026-06-10 (manual from snapshot diff).
# Source this file or paste into your profile to pin the loopback devices.
#
# Verification — check that by-path symlinks still exist before a loopback run:
#   ssh dc0sk@dc0sk-rpi51 "ls /dev/snd/by-path/ | grep -Fq 'xhci-hcd.0-usb-0:2:1.0' && echo ok || echo MISSING"
#   ssh dc0sk@dc0sk-rpi52 "ls /dev/snd/by-path/ | grep -Fq 'xhci-hcd.1-usb-0:2:1.0' && echo ok || echo MISSING"

# rpi51 (ISS, loopback TX — line-out of USB dongle → cable → rpi52 line-in)
# VID:PID 0d8c:0014  C-Media USB Audio Adapter (Unitek Y-247A)
# NOTE: rpi51 has two identical 0d8c:0014 dongles; Device_1 is a different dongle.
#       The loopback cable dongle is "Device" (the one on xhci-hcd.0, USB port 0:2).
export ISS_DEVICE="plughw:CARD=Device,DEV=0"
export ISS_DEVICE_BYID="usb-C-Media_Electronics_Inc._USB_Audio_Device-00"
export ISS_DEVICE_BYPATH="platform-xhci-hcd.0-usb-0:2:1.0"

# rpi52 (IRS, loopback RX — cable from rpi51 → line-in of USB dongle)
# VID:PID 0d8c:013c  C-Media CM108 Audio Controller
export IRS_DEVICE="plughw:CARD=Device,DEV=0"
export IRS_DEVICE_BYID="usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00"
export IRS_DEVICE_BYPATH="platform-xhci-hcd.1-usb-0:2:1.0"
